filtered_model_methods_analyses = { 'edsr': { 'edsr_x2c64b16_1xb16-300k_div2k.py': { 'flag': True,
                                                   'flops': '22.489G',
                                                   'params': '1.37M'},
            'edsr_x3c64b16_1xb16-300k_div2k.py': { 'flag': True,
                                                   'flops': '25.65G',
                                                   'params': '1.554M'},
            'edsr_x4c64b16_1xb16-300k_div2k.py': { 'flag': True,
                                                   'flops': '32.492G',
                                                   'params': '1.518M'}},
  'srcnn': { 'srcnn_x4k915_1xb16-1000k_div2k.py': { 'flag': True,
                                                    'flops': '5.243G',
                                                    'params': '20.099K'}},
  'srgan_resnet': { 'msrresnet_x4c64b16_1xb16-1000k_div2k.py': { 'flag': True,
                                                                 'flops': '41.555G',
                                                                 'params': '1.518M'},
                    'srgan_x4c64b16_1xb16-1000k_div2k.py': { 'flag': True,
                                                             'flops': '41.555G',
                                                             'params': '1.518M'}},
  'swinir': { 'swinir_x2s64w8d4e60_8xb4-lr2e-4-500k_div2k.py': { 'flag': True,
                                                                 'flops': '17.377G',
                                                                 'params': '0.91M'},
              'swinir_x3s64w8d4e60_8xb4-lr2e-4-500k_div2k.py': { 'flag': True,
                                                                 'flops': '17.51G',
                                                                 'params': '0.918M'},
              'swinir_x4s64w8d4e60_8xb4-lr2e-4-500k_div2k.py': { 'flag': True,
                                                                 'flops': '17.696G',
                                                                 'params': '0.93M'}}}
