model_methods_analyses = { 'edsr': { 'edsr_x2c64b16_1xb16-300k_div2k.py': { 'flag': True,
                                                   'flops': '22.489G',
                                                   'params': '1.37M'},
            'edsr_x3c64b16_1xb16-300k_div2k.py': { 'flag': True,
                                                   'flops': '25.65G',
                                                   'params': '1.554M'},
            'edsr_x4c64b16_1xb16-300k_div2k.py': { 'flag': True,
                                                   'flops': '32.492G',
                                                   'params': '1.518M'}},
  'esrgan': { 'esrgan_psnr-x4c64b23g32_1xb16-1000k_div2k.py': { 'flag': False,
                                                                'flops': '0.294T',
                                                                'params': '16.698M'},
              'esrgan_x4c64b23g32_1xb16-400k_div2k.py': { 'flag': False,
                                                          'flops': '0.294T',
                                                          'params': '16.698M'}},
  'rdn': { 'rdn_x2c64b16_1xb16-1000k_div2k.py': { 'flag': False,
                                                  'flops': '0.362T',
                                                  'params': '22.123M'},
           'rdn_x3c64b16_1xb16-1000k_div2k.py': { 'flag': False,
                                                  'flops': '0.366T',
                                                  'params': '22.308M'},
           'rdn_x4c64b16_1xb16-1000k_div2k.py': { 'flag': False,
                                                  'flops': '0.372T',
                                                  'params': '22.271M'}},
  'real_esrgan': { 'realesrgan_c64b23g32_4xb12-lr1e-4-400k_df2k-ost.py': { 'flag': False,
                                                                           'flops': '0.294T',
                                                                           'params': '16.698M'},
                   'realesrnet_c64b23g32_4xb12-lr2e-4-1000k_df2k-ost.py': { 'flag': False,
                                                                            'flops': '0.294T',
                                                                            'params': '16.698M'}},
  'srcnn': { 'srcnn_x4k915_1xb16-1000k_div2k.py': { 'flag': True,
                                                    'flops': '5.243G',
                                                    'params': '20.099K'}},
  'srgan_resnet': { 'msrresnet_x4c64b16_1xb16-1000k_div2k.py': { 'flag': True,
                                                                 'flops': '41.555G',
                                                                 'params': '1.518M'},
                    'srgan_x4c64b16_1xb16-1000k_div2k.py': { 'flag': True,
                                                             'flops': '41.555G',
                                                             'params': '1.518M'}},
  'swinir': { 'swinir_gan-x2s64w8d6e180_8xb4-lr1e-4-600k_df2k-ost.py': { 'flag': False,
                                                                         'flops': '0.208T',
                                                                         'params': '11.679M'},
              'swinir_gan-x4s64w8d6e180_8xb4-lr1e-4-600k_df2k-ost.py': { 'flag': False,
                                                                         'flops': '0.225T',
                                                                         'params': '11.716M'},
              'swinir_gan-x4s64w8d9e240_8xb4-lr1e-4-600k_df2k-ost.py': { 'flag': False,
                                                                         'flops': '0.505T',
                                                                         'params': '28.013M'},
              'swinir_psnr-x2s64w8d6e180_8xb4-lr1e-4-600k_df2k-ost.py': { 'flag': False,
                                                                          'flops': '0.208T',
                                                                          'params': '11.679M'},
              'swinir_psnr-x4s64w8d6e180_8xb4-lr1e-4-600k_df2k-ost.py': { 'flag': False,
                                                                          'flops': '0.225T',
                                                                          'params': '11.716M'},
              'swinir_psnr-x4s64w8d9e240_8xb4-lr1e-4-600k_df2k-ost.py': { 'flag': False,
                                                                          'flops': '0.505T',
                                                                          'params': '28.013M'},
              'swinir_s126w7d6e180_8xb1-lr2e-4-1600k_dfwb-colorCAR10.py': { 'flag': False,
                                                                            'flops': '0.214T',
                                                                            'params': '11.492M'},
              'swinir_s126w7d6e180_8xb1-lr2e-4-1600k_dfwb-colorCAR20.py': { 'flag': False,
                                                                            'flops': '0.214T',
                                                                            'params': '11.492M'},
              'swinir_s126w7d6e180_8xb1-lr2e-4-1600k_dfwb-colorCAR30.py': { 'flag': False,
                                                                            'flops': '0.214T',
                                                                            'params': '11.492M'},
              'swinir_s126w7d6e180_8xb1-lr2e-4-1600k_dfwb-colorCAR40.py': { 'flag': False,
                                                                            'flops': '0.214T',
                                                                            'params': '11.492M'},
              'swinir_s128w8d6e180_8xb1-lr2e-4-1600k_dfwb-colorDN15.py': { 'flag': False,
                                                                           'flops': '0.201T',
                                                                           'params': '11.504M'},
              'swinir_s128w8d6e180_8xb1-lr2e-4-1600k_dfwb-colorDN25.py': { 'flag': False,
                                                                           'flops': '0.201T',
                                                                           'params': '11.504M'},
              'swinir_s128w8d6e180_8xb1-lr2e-4-1600k_dfwb-colorDN50.py': { 'flag': False,
                                                                           'flops': '0.201T',
                                                                           'params': '11.504M'},
              'swinir_x2s48w8d6e180_8xb4-lr2e-4-500k_div2k.py': { 'flag': False,
                                                                  'flops': '0.205T',
                                                                  'params': '11.752M'},
              'swinir_x2s64w8d4e60_8xb4-lr2e-4-500k_div2k.py': { 'flag': True,
                                                                 'flops': '17.377G',
                                                                 'params': '0.91M'},
              'swinir_x2s64w8d6e180_8xb4-lr2e-4-500k_df2k.py': { 'flag': False,
                                                                 'flops': '0.205T',
                                                                 'params': '11.752M'},
              'swinir_x3s48w8d6e180_8xb4-lr2e-4-500k_div2k.py': { 'flag': False,
                                                                  'flops': '0.208T',
                                                                  'params': '11.937M'},
              'swinir_x3s64w8d4e60_8xb4-lr2e-4-500k_div2k.py': { 'flag': True,
                                                                 'flops': '17.51G',
                                                                 'params': '0.918M'},
              'swinir_x3s64w8d6e180_8xb4-lr2e-4-500k_df2k.py': { 'flag': False,
                                                                 'flops': '0.208T',
                                                                 'params': '11.937M'},
              'swinir_x4s48w8d6e180_8xb4-lr2e-4-500k_div2k.py': { 'flag': False,
                                                                  'flops': '0.215T',
                                                                  'params': '11.9M'},
              'swinir_x4s64w8d4e60_8xb4-lr2e-4-500k_div2k.py': { 'flag': True,
                                                                 'flops': '17.696G',
                                                                 'params': '0.93M'},
              'swinir_x4s64w8d6e180_8xb4-lr2e-4-500k_df2k.py': { 'flag': False,
                                                                 'flops': '0.215T',
                                                                 'params': '11.9M'}}}
